name: http_source
description: Interfaces for create a http manga source.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  manga_source:
    path: ../manga_source/
  equatable: ^2.0.3